version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "EMRDataAnalysisJupyter"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1234567890123"
s3_prefix = "EMRDataAnalysisJupyter"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"

