AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  DeployToLambda. Showcase using CodeDeploy to update Lambda function
Metadata:
  AWS::ServerlessRepo::Application:
    Name: "CodeDeploy-DeployToLambda"
    Description: Showcase using CodeDeploy to update Lambda function
    Author: rostskadat
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    Labels: [ "SAPC01", "CodeDeploy" ]
    HomePageUrl: https://github.com/rostskadat
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/rostskadat

Resources:
  # Details about the myDateTimeFunction Lambda function
  myDateTimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/myDateTimeFunction
      Handler: myDateTimeFunction.handler
      Runtime: nodejs10.x
      # Instructs your myDateTimeFunction is published to an alias named "live".      
      AutoPublishAlias: live
      # Grants this function permission to call lambda:InvokeFunction
      Policies:
        - Version: "2012-10-17"
          Statement: 
          - Effect: "Allow"
            Action: 
              - "lambda:InvokeFunction"
            Resource: '*'
      DeploymentPreference:
          # Specifies the deployment configuration      
          Type: Linear10PercentEvery1Minute
          # Specifies Lambda functions for deployment lifecycle hooks
          Hooks:
            PreTraffic: 
              Ref: beforeAllowTraffic
            PostTraffic: 
              Ref: afterAllowTraffic
            
  # Specifies the BeforeAllowTraffic lifecycle hook Lambda function
  beforeAllowTraffic:
    Type: AWS::Serverless::Function
    Properties:
      Handler: beforeAllowTraffic.handler
      Policies:
        - Version: 2012-10-17
          # Grants this function permission to call codedeploy:PutLifecycleEventHookExecutionStatus        
          Statement: 
          - Effect: Allow
            Action: 
              - "codedeploy:PutLifecycleEventHookExecutionStatus"
            Resource:
              Fn::Sub: 'arn:${AWS::Partition}:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
        - Version: 2012-10-17
          # Grants this function permission to call lambda:InvokeFunction        
          Statement: 
          - Effect: Allow
            Action: 
              - "lambda:InvokeFunction"
            Resource:
              Ref: myDateTimeFunction.Version
      Runtime: nodejs10.x
      # Specifies the name of the Lambda hook function
      CodeUri: lambdas/beforeAllowTraffic
      FunctionName: 'CodeDeployHook_beforeAllowTraffic'
      # DeploymentPreference:
      #   Enabled: true
      #   Type: AllAtOnce
      Timeout: 5
      Environment:
        Variables:
          NewVersion: 
            Ref: myDateTimeFunction.Version
          
  # Specifies the AfterAllowTraffic lifecycle hook Lambda function
  afterAllowTraffic:
    Type: AWS::Serverless::Function
    Properties:
      Handler: afterAllowTraffic.handler
      Policies:
        - Version: 2012-10-17
          Statement: 
          # Grants this function permission to call codedeploy:PutLifecycleEventHookExecutionStatus         
          - Effect: Allow
            Action: 
              - "codedeploy:PutLifecycleEventHookExecutionStatus"
            Resource:
              Fn::Sub: 'arn:${AWS::Partition}:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
        - Version: 2012-10-17
          Statement: 
          # Grants this function permission to call lambda:InvokeFunction          
          - Effect: Allow
            Action: 
              - "lambda:InvokeFunction"
            Resource: 
              Ref: myDateTimeFunction.Version
      Runtime: nodejs10.x
      # Specifies the name of the Lambda hook function
      CodeUri: lambdas/afterAllowTraffic
      FunctionName: 'CodeDeployHook_afterAllowTraffic'
      # DeploymentPreference:
      #   Enabled: true
      #   Type: AllAtOnce
      Timeout: 5
      Environment:
        Variables:
          NewVersion: 
            Ref: myDateTimeFunction.Version


  #arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda