AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ELBQ20WAF
Resources:
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Scope: CLOUDFRONT
      Description: Rules to prevent cross scripting and sql injection
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: 
          Fn::Sub: "${AWS::StackName}-WebACL"
      Rules:
        # - Name: AWS-AWSManagedRulesSQLiRuleSet
        #   Priority: 0
        #   Action:
        #     Block: {}
        #   VisibilityConfig:
        #     SampledRequestsEnabled: true
        #     CloudWatchMetricsEnabled: true
        #     MetricName: AWS-AWSManagedRulesSQLiRuleSet
        #   Statement:
        #     ManagedRuleGroupStatement:
        #       VendorName: AWS
        #       Name: AWSManagedRulesSQLiRuleSet
        - Name: BlockXssAttack
          Priority: 1
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: BlockXssAttackMetric
          Statement:
            XssMatchStatement:
              FieldToMatch:
                AllQueryArguments: {}
              TextTransformations:
                - Priority: 1
                  Type: NONE

Outputs:
  WebACL:
    Description: The WebACL
    Value:
      Fn::GetAtt: WebACL.Arn
