AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  UpdateAppStrategies. Showcase the different update strategies of an application.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Parameters related to Route53
        Parameters:
          - HostedZoneName
          - SubDomainName
          - CertificateArn
      - Label:
          default: Parameters related to VPC
        Parameters:
          - VpcId
          - Subnets
      - Label:
          default: Parameters related to AutoScalingGroup
        Parameters:
          - MinSize
          - DesiredCapacity
          - MaxSize
      - Label:
          default: Parameters related to EC2
        Parameters:
          - ImageId
          - InstanceType
          - KeyName
      - Label:
          default: Parameters related to LaunchTemplate
        Parameters:
          - AppVersion

Parameters:

  HostedZoneName:
    Description: "The hosted zone name"
    Type: String
    Default: domain.com

  SubDomainName:
    Description: "The subdomain of the API"
    Type: String
    Default: sapc01-updstrategy

  CertificateArn:
    Description: "THe ACM Certificate Arn"
    Type: String
    Default: "arn:aws:acm:eu-west-1:123456789012:certificate/12345678-1234-1234-1234-123456789012"
      
  VpcId:
    Description: "The VPC in which to put the load balancer"
    Type: AWS::EC2::VPC::Id
    Default: vpc-9e9b9ffa

  Subnets:
    Description: "The Subnets in which to put the load balancer"
    Type: List<AWS::EC2::Subnet::Id>
    Default: "subnet-b09099d4,subnet-f76b6581,subnet-58421700"

  ImageId:
    Description: "The EC2 Instance AMI"
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"

  InstanceType:
    Description: "The EC2 Instance Type"
    Type: "String"
    Default: "t3.micro"

  KeyName:
    Description: "The Key to use to connect to the EC2 Instance"
    Type: AWS::EC2::KeyPair::KeyName
    Default: "SAPC01"

  MinSize:
    Description: "The minimum number of instance in the AutoScalingGroup"
    Type: Number
    Default: 1

  DesiredCapacity:
    Description: "The desired number of instance in the AutoScalingGroup"
    Type: Number
    Default: 2

  MaxSize:
    Description: "The maximum number of instance in the AutoScalingGroup"
    Type: Number
    Default: 4

  AppVersion:
    Description: "A String identifying the application version"
    Type: String
    Default: "Initial Version"

Resources:

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        HostedZoneId: 
          Fn::GetAtt: LoadBalancer.CanonicalHostedZoneID
        DNSName: 
          Fn::GetAtt: LoadBalancer.DNSName
      HostedZoneName: 
        # NOTE: the final dot
        Fn::Sub: "${HostedZoneName}."
      Name: 
        Fn::Sub: "${SubDomainName}.${HostedZoneName}"
      Type: A

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        Ref: Subnets
      Type: application
      Tags: 
        - Key: PLATFORM
          Value: SAPC01

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      HealthCheckPath: /
      Matcher:
        HttpCode: '200-299'
      Tags:
        - Key: PLATFORM
          Value: SAPC01
      TargetType: instance
      VpcId:
        Ref: VpcId

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: 
            Ref: CertificateArn
      DefaultActions:
      - TargetGroupArn:   
          Ref: TargetGroup
        Type: forward
      LoadBalancerArn: 
        Ref: LoadBalancer
      Port: 443
      Protocol: HTTPS

  AutoScalingGroup: 
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      HealthCheckType: ELB
      HealthCheckGracePeriod: 60
      LaunchTemplate: 
        LaunchTemplateId:
          Ref: LaunchTemplate
        Version:
          Fn::GetAtt: LaunchTemplate.LatestVersionNumber
      MetricsCollection:
        - Granularity: 1Minute
          Metrics:
            - GroupInServiceInstances
      MinSize:
        Ref: MinSize
      MaxSize: 
        Ref: MaxSize
      DesiredCapacity: 
        Ref: DesiredCapacity
      Tags: 
        - Key: PLATFORM
          Value: SAPC01
          PropagateAtLaunch: true
        - Key: ScalingStrategy
          Value: Target
          PropagateAtLaunch: true
      TargetGroupARNs:
        - Ref: TargetGroup
      VPCZoneIdentifier:
        Ref: Subnets

  ScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: 
        Ref: AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 1

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default: [Install]
        Install:
          files:
            /etc/yum.repos.d/nginx.repo:
              content: |
                [nginx]
                name=nginx repo
                baseurl=http://nginx.org/packages/mainline/centos/7/$basearch/
                gpgcheck=0
                enabled=1
              mode: "000644"
              owner: root
              group: root
            /etc/nginx/conf.d/default.conf:
              content: 
                Fn::Sub: |
                  server {
                    listen       80;
                    server_name  ${SubDomainName}.${HostedZoneName};
                    access_log   /var/log/nginx/access.log;
                    error_log    /var/log/nginx/error.log;
                    location / {
                      root   /usr/share/nginx/html;
                      index  index.html index.htm;
                    }
                    error_page   500 502 503 504  /50x.html;
                    location = /50x.html {
                      root   /usr/share/nginx/html;
                    }
                  }
              mode: "000644"
              owner: root
              group: root
            /usr/share/nginx/html/index.html.app:
              content: 
                Fn::Sub: |
                  <!DOCTYPE html>
                  <html>
                  <head><title>Welcome to nginx!</title><style>
                    body {
                      width: 35em;
                      margin: 0 auto;
                      font-family: Tahoma, Verdana, Arial, sans-serif;
                    }
                  </style>
                  <script type = "text/JavaScript">
                    function AutoRefresh( ms ) { setTimeout("location.reload(true);", ms); }
                  </script>
                  </head>
                  <body onload="javascript:AutoRefresh(5000);">
                  <h1><code><b>{{instance_id}}</b>: {{app_version}}</code></h1>
                  </body>
                  </html>
              mode: "000644"
              owner: root
              group: root
            /root/bootstrap.sh:
              content: 
                Fn::Sub: |
                  #!/bin/bash
                  yum install -y nginx
                  instance_id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
                  app_version=$(cat /tmp/app_version.txt)
                  index_path=/usr/share/nginx/html/index.html
                  sed -e "s/{{instance_id}}/$instance_id/;s/{{app_version}}/$app_version/" $index_path.app > $index_path
                  systemctl enable nginx
                  systemctl start nginx
              mode: "000700"
              owner: root
              group: root
          commands:
            01_bootstrap:
              command: "bash /root/bootstrap.sh"
    Properties:
      LaunchTemplateData:
        ImageId: 
          Ref: ImageId
        InstanceType:
          Ref: InstanceType
        KeyName: 
          Ref: KeyName
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: PLATFORM
                Value: SAPC01
          - ResourceType: volume
            Tags:
              - Key: PLATFORM
                Value: SAPC01
        UserData:
          Fn::Base64:
            Fn::Sub: |
              #!/bin/bash
              yum-config-manager --enable epel ; yum update -y ; yum install -y aws-cfn-bootstrap
              cat > /tmp/app_version.txt <<EOF
              ${AppVersion}
              EOF
              /opt/aws/bin/cfn-init --verbose --region ${AWS::Region} --stack ${AWS::StackName} --resource LaunchTemplate
              echo "Done"

Outputs:

  LoadBalancerDNSName:
    Description: "The LoadBalancer DNSName"
    Value: 
      Fn::GetAtt: LoadBalancer.DNSName

  RecordSet:
    Description: "The URL where the application is available"
    Value: 
      Fn::Sub: "https://${RecordSet}"
