version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "BillingAlarm"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xtx4sl8voopg"
s3_prefix = "BillingAlarm"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"

tags = "PROJECT=\"SAPC01\" APPLICATION=\"SAPC01\" ENVIRONMENT=\"POC\""
