AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SFTPServer. A simple SFTP Server backed by S3
Metadata:
  AWS::ServerlessRepo::Application:
    Name: "Transfer-SFTPServer"
    Description: A simple SFTP Server backed by S3
    Author: rostskadat
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    Labels: [ "SAPC01", "Transfer" ]
    HomePageUrl: https://github.com/rostskadat
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/rostskadat

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
  Server:
    Type: AWS::Transfer::Server
    Properties:
      Domain: S3
      EndpointType: PUBLIC
      LoggingRole:
        Fn::GetAtt: LoggingRole.Arn
      Protocols:
        - SFTP
      IdentityProviderType: SERVICE_MANAGED
  LoggingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - transfer.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - transfer.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AllowS3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowListingOfUserFolder
                Action:
                  - s3:ListBucket
                Effect: Allow
                Resource:
                  - Fn::Sub: "${Bucket.Arn}"
              - Sid: HomeDirObjectAccess
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:DeleteObjectVersion
                  - s3:GetObjectVersion
                  - s3:GetObjectACL
                  - s3:PutObjectACL
                Resource:
                  Fn::Sub: "${Bucket.Arn}/*"

  User:
    Type: AWS::Transfer::User
    Properties:
      HomeDirectory:
        Fn::Sub: "/${Bucket}"
      HomeDirectoryType: PATH
      # Policy:
      #   Fn::Sub: |
      #     Version: "2012-10-17"
      #     Statement:
      #       - Sid: AllowListingOfUserFolder
      #         Action:
      #           - s3:ListBucket
      #         Effect: Allow
      #         Resource:
      #           - arn:aws:s3:::${Transfer:HomeBucket}
      #         Condition:
      #           StringLike:
      #             s3:prefix:
      #               - "${Transfer:HomeFolder}/*"
      #               - "${Transfer:HomeFolder}"
      #       - Sid: HomeDirObjectAccess
      #         Effect: Allow
      #         Action:
      #           - s3:PutObject
      #           - s3:GetObject
      #           - s3:DeleteObject
      #           - s3:DeleteObjectVersion
      #           - s3:GetObjectVersion
      #           - s3:GetObjectACL
      #           - s3:PutObjectACL
      #         Resource: arn:aws:s3:::${Transfer:HomeDirectory}/*
      Role:
        Fn::GetAtt: Role.Arn
      ServerId:
        Fn::GetAtt: Server.ServerId
      SshPublicKeys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTX688a9cmU2DG8EfoCGKm7NUQu+iBDAHDf/lsPfuUnXfr//bIEcSUuYVc905NXwqQlI/kE9KL80qkEARXTZRgDaJBhE6DMqk4AmGOM1/lzujskuwZw+d0tVeyN0h2cROPj4oIj583zBv9Gf8KWu0Q/r6Gv/ABFOXTJv1B/h4ARVwV4Dzmo72iFKDPS2SMN8pAf4K7DRMs3WrMC68+y5XnlHpND6cgIw9uM6EvMrdpDzOWHOu3np2Z+KOAcaV1v6nk7wf4x7IbfFTQkGKHuUaFhbKDzYdqFW6oPmk1zb47Q5U44+oZTvIzKvQwexrarTo+/aio3KiKcAf1bMrltz+x
      UserName: allftp

Outputs:
  Bucket:
    Description: The Bucket
    Value:
      Ref: Bucket
  Server:
    Description: The Server
    Value:
      Ref: Server
  User:
    Description: The User
    Value:
      Ref: User
