version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SAPC01-LambdaAtEdgeWithS3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-octnt6ddov0y"
s3_prefix = "SAPC01/LambdaAtEdgeWithS3"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"

tags = "PROJECT=\"SAPC01\" APPLICATION=\"SAPC01\" ENVIRONMENT=\"POC\""
