AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Architecture. The bucket were all application should be uploaded
Resources:

  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      Tags:
        - Key: PLATFORM
          Value: SAPC01

Outputs:
  Bucket:
    Description: The Bucket
    Value:
      Ref: Bucket
