version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SAPC01-Integrations-ecr"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xtx4sl8voopg"
s3_prefix = "SAPC01-Integrations-ecr"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "VpcId=\"vpc-9e9b9ffa\" Subnets=\"subnet-b09099d4,subnet-f76b6581,subnet-58421700\" StageName=\"Prod\""

tags = "PROJECT=\"SAPC01\" APPLICATION=\"SAPC01\" ENVIRONMENT=\"POC\""
