version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Route53"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1234567890123"
s3_prefix = "Route53"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
