---
apiVersion: v1
kind: Namespace
metadata:
  name: sample
#  labels:
#    pod-type: fargate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: sample
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
        #pod-type: fargate
    spec:
      containers:
        - name: hello-world
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: sample
spec:
  selector:
    name: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080