version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SAPC01-CrossAccountForensic-root"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xtx4sl8voopg"
s3_prefix = "SAPC01-CrossAccountForensic-root"
region = "eu-west-1"
profile = "n090536@123456789012"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "RootAccount=\"123456789012\" RootOU=\"o-abcdefghij\" ChildAccountId=\"123456789012\""
tags = "PROJECT=\"SAPC01\" APPLICATION=\"SAPC01\" ENVIRONMENT=\"POC\""
