AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  MultipleAttemptID. Showcase how the SQS AttemptId is used to retry a failed message
Metadata:
  AWS::ServerlessRepo::Application:
    Name: "SQS-MultipleAttemptID"
    Description: Showcase how the SQS AttemptId is used to retry a failed message
    Author: rostskadat
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    Labels: ["SAPC01", "SQS"]
    HomePageUrl: https://github.com/rostskadat
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/rostskadat

Resources:

  PrintQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: true
      FifoQueue: true
      Tags:
        - Key: PLATFORM
          Value: SAPC01

Outputs:
  PrintQueue:
    Description: The PrintQueue
    Value:
      Ref: PrintQueue
