version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "S3TransferAcceleration"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1234567890123"
s3_prefix = "S3TransferAcceleration"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
