AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CfManagedBlockchainResources. This stack provides Cloudformation Custom Resources to create ManagedBlockchain Resources (Proposal)
Metadata:
  AWS::ServerlessRepo::Application:
    Name: "KinesisVideoStream-CfManagedBlockchainResources"
    Description: This stack provides Cloudformation Custom Resources to create ManagedBlockchain Resources (Proposal)
    Author: rostskadat
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    Labels: [ "ManagedBlockchain" ]
    HomePageUrl: https://github.com/rostskadat
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/rostskadat

Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.8
    Timeout: 30
    Layers:
      - Ref: CfManagedBlockchainResourcesLayer01
    Tags:
      PLATFORM: SAPC01

Resources:

  CfManagedBlockchainResourcesLayer01:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: python3.8
    Properties:
      ContentUri: layers/CfManagedBlockchainResourcesLayer01
      CompatibleRuntimes:
        - python3.8
      RetentionPolicy: Delete

  CfManagedBlockchainProposal:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CfManagedBlockchainProposal
      Description: A CloudFormation Custom Resource to create a ManagedBlockchain Proposal.
      CodeUri: lambdas/CfManagedBlockchainProposal
      Policies:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::aws:policy/AmazonManagedBlockchainFullAccess"

Outputs:

  CfManagedBlockchainProposal:
    Description: The CfManagedBlockchainProposal function ARN
    Value:
      Fn::GetAtt: CfManagedBlockchainProposal.Arn
