AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CfKinesisResources. This stack provides Cloudformation Custom Resources to create Kinesis Video Resources in your CloudFormation template.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: "KinesisVideoStream-CfKinesisResources"
    Description: This stack provides Cloudformation Custom Resources to create Kinesis Video Resources in your CloudFormation template.
    Author: rostskadat
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    Labels: [ "KinesisVideoStream" ]
    HomePageUrl: https://github.com/rostskadat
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/rostskadat


Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.8
    Timeout: 30
    Layers:
      - Ref: CfCurResourcesLayer01
    Tags:
      PLATFORM: SAPC01

Resources:

  CfCurResourcesLayer01:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: python3.8
    Properties:
      ContentUri: layers/CfCurResourcesLayer01
      CompatibleRuntimes:
        - python3.8
      RetentionPolicy: Delete

  CfCostAndUsageReport:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CfCostAndUsageReport
      Description: A CloudFormation Custom Resource to create a Cost And Usage Report
      CodeUri: lambdas/CfCostAndUsageReport
      Policies:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::aws:policy/job-function/Billing"

Outputs:

  CfCostAndUsageReport:
    Description: The CfCostAndUsageReport function ARN
    Value:
      Fn::GetAtt: CfCostAndUsageReport.Arn
