AWSTemplateFormatVersion: '2010-09-09'
Transform: 
  - AWS::Serverless-2016-10-31
  - S3Objects
  - Yaml2Json
Description: >
  Secrets
Parameters:
  LinuxImageId:
    Description: "The Image Id (AMI) to use"
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"

  WindowsImageId:
    Description: "The Image Id (AMI) to use"
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-windows-latest/Windows_Server-2019-English-STIG-Core"

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      Tags:
        - Key: PLATFORM
          Value: SAPC01

  StringParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: StringParameterValue
      AllowedPattern: "^.*$"
      Tags:
        PLATFORM: SAPC01

  StringListParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: StringList
      Value: StringListParameterValue1,StringListParameterValue2
      AllowedPattern: "^.*$"
      Tags:
        PLATFORM: SAPC01

  LinuxImageParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: 
        Ref: LinuxImageId
      AllowedPattern: "^.*$"
      Tags:
        PLATFORM: SAPC01

  WindowsImageParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: 
        Ref: WindowsImageId
      AllowedPattern: "^.*$"
      Tags:
        PLATFORM: SAPC01


  # Since it fails to resolve in CustomResource
  PlainTextParameterStoreSecureString:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: "{resolve:ssm-secure:ParameterStoreSecureString:1}"
      AllowedPattern: "^.*$"
      Tags:
        PLATFORM: SAPC01

  SecretsManagerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: SecretsManagerSecret
      SecretString: 
        Fn::Yaml2Json:
          username: "username"
          password: "Passw0rd"

  # Since it fails to resolve in CustomResource
  PlainTextSecretsManagerSecret:
    Type: AWS::SSM::Parameter
    DependsOn: SecretsManagerSecret
    Properties:
      Type: String
      Value: "{{resolve:secretsmanager:SecretsManagerSecret:SecretString:password}}"
      AllowedPattern: "^.*$"
      Tags:
        PLATFORM: SAPC01


#  ExpiringParameter:
#    Type: AWS::SSM::Parameter
#    Properties:
#      Type: String
#      Value: StringParameterValue
#      AllowedPattern: "^.*$"
#      Policies:
#        Fn::Yaml2Json:
#          - Type: Expiration
#            Version: '1.0'
#            Attributes:
#              Timestamp: '2020-10-20T12:00:00Z'
#          - Type: ExpirationNotification
#            Version: '1.0'
#            Attributes:
#              Before: '1'
#              Unit: Hour
#          - Type: NoChangeNotification
#            Version: '1.0'
#            Attributes:
#              After: '2'
#              Unit: Hours

  ParameterDump:
    Type: AWS::S3::Object
    DependsOn: SecretsManagerSecret
    Properties:
      Target:
        Bucket:
          Ref: Bucket
        Key: ParameterStore.md
        ContentType: text/x-markdown
      Body:
        Fn::Sub: |
          # From `Parameters` Section

          * LinuxImageId=`${LinuxImageId}`
          * WindowsImageId=`${WindowsImageId}`

          # From `AWS::SSM::Parameters` in Resources Section

          * LinuxImageParameter (`${LinuxImageParameter}`) =`${LinuxImageParameter.Value}`
          * WindowsImageParameter (`${WindowsImageParameter}`) =`${WindowsImageParameter.Value}`

          # Indirectly: 

          * PlainTextParameterStoreSecureString (`${PlainTextParameterStoreSecureString}`) = `${PlainTextParameterStoreSecureString.Value}`
          * PlainTextSecretsManagerSecret (`${PlainTextSecretsManagerSecret}`) = `${PlainTextSecretsManagerSecret.Value}`
          * SecretsManagerSecret = `{\{resolve:ssm-secure:/aws/reference/secretsmanager/SecretsManagerSecret}\}`          
          
          # Resolved inline:

          * LinuxImageId=`{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}`
          * WindowsImageId=`{{resolve:ssm:/aws/service/ami-windows-latest/Windows_Server-2019-English-STIG-Core}}`

          # Different parameter type:

          * StringParameter = ${StringParameter.Value}
          * StringListParameter = ${StringListParameter.Value}

          # Using `SecretsManager`:
          
          *BEWARE*, the construct `{\{resolve:ssm-secure:ParameterStoreSecureString:1}\}` fails on Custom Resource
          
          *BEWARE*, the construct `{\{resolve:secretsmanager:SecretsManagerSecret:SecretString:password}\}` will not work.

Outputs:
  Bucket:
    Description: "The Bucket Id"
    Value: 
      Ref: Bucket

  ParameterDump:
    Description: The S3 Object containing the parameters
    Value:
      Ref: ParameterDump