AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  OpsWorksHelloWorld. Simple Hello World OpsWorks stack
Metadata:
  AWS::ServerlessRepo::Application:
    Name: "OpsWorksHelloWorld"
    Description: Simple Hello World OpsWorks stack
    Author: rostskadat
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    Labels: [ "SAPC01", "OpsWorks" ]
    HomePageUrl: https://github.com/rostskadat
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/rostskadat

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      Tags:
        - Key: PLATFORM
          Value: SAPC01

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref Bucket
      PolicyDocument: 
        Statement:
          - Effect: Allow
            Action:
              - "s3:*"
            Resource: 
              - !Sub "${Bucket.Arn}"
              - !Sub "${Bucket.Arn}/*"
            Principal: '*'

Outputs:

  Bucket:
    Description: The Bucket
    Value: !Ref Bucket
