AWSTemplateFormatVersion: '2010-09-09'
Transform: 
  - AWS::Serverless-2016-10-31
  - SamPolicyTemplateTranslator
  - Yaml2Json
Description: >
  CSV2DynamoDB. Showcase import of CSV into DynamoDB using DMS, when endpoint for specific DB does not exists
Metadata:
  AWS::ServerlessRepo::Application:
    Name: "DatabaseMigrationService-CSV2DynamoDB"
    Description: Showcase import of CSV into DynamoDB using DMS, when endpoint for specific DB does not exists
    Author: rostskadat
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    Labels: [ "SAPC01", "DatabaseMigrationService" ]
    HomePageUrl: https://github.com/rostskadat
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/rostskadat

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Parameters related to S3 Target
        Parameters:
          - LogBucket
      - Label:
          default: Parameters related to DMS
        Parameters:
          - SchemaName
          - TableName

Parameters:
  LogBucket:
    Description: The LogBucket
    Type: String
    Default: aws-logs-123456789012-eu-west-1

  SchemaName:
    Description: The SchemaName
    Type: String
    Default: sonarqube

  TableName:
    Description: The TableName
    Type: String
    Default: issues

Resources:

  DmsVpcRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: dms-vpc-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - dms.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonDMSVPCManagementRole
      Path: "/"

  DmsCloudwatchLogsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: dms-cloudwatch-logs-role 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - dms.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - S3CrudPolicy:
            BucketName:
              Ref: LogBucket
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonDMSCloudWatchLogsRole
      Path: "/"

  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      Tags:
        - Key: PLATFORM
          Value: SAPC01

  BucketRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - dms.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - S3CrudPolicy:
            BucketName:
              Ref: Bucket
      Path: "/"

  S3Endpoint: 
    Type: AWS::DMS::Endpoint
    Properties: 
      EndpointType: source
      EngineName: s3
      S3Settings:
        BucketName: 
          Ref: Bucket
        ExternalTableDefinition: 
          # As per https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.S3.html#CHAP_Source.S3.DataTypes
          Fn::Sub:
            Fn::Yaml2Json:
              TableCount: '1'
              Tables:
              - TableName: "${TableName}"
                TablePath: "${SchemaName}/${TableName}/"
                TableOwner: "${SchemaName}"
                TableColumns:
                - ColumnName: id
                  ColumnType: STRING
                  ColumnLength: 20
                  ColumnNullable: false
                  ColumnIsPk: true
                - ColumnName: kee
                  ColumnType: STRING
                  ColumnLength: 50
                  ColumnNullable: false
                - ColumnName: rule_id
                  ColumnType: INT8
                  ColumnNullable: true
                - ColumnName: severity
                  ColumnType: STRING
                  ColumnLength: 50
                  ColumnNullable: true
                - ColumnName: manual_severity
                  ColumnType: BOOLEAN
                  ColumnNullable: false
                - ColumnName: message
                  ColumnType: STRING
                  ColumnLength: 4000
                  ColumnNullable: true
                - ColumnName: line
                  ColumnType: INT8
                  ColumnNullable: true
                - ColumnName: gap
                  ColumnType: STRING
                  ColumnLength: 20
                  ColumnNullable: true
                - ColumnName: status
                  ColumnType: STRING
                  ColumnLength: 20
                  ColumnNullable: true
                - ColumnName: resolution
                  ColumnType: STRING
                  ColumnLength: 20
                  ColumnNullable: true
                - ColumnName: checksum
                  ColumnType: STRING
                  ColumnLength: 1000
                  ColumnNullable: true
                - ColumnName: reporter
                  ColumnType: STRING
                  ColumnLength: 255
                  ColumnNullable: true
                - ColumnName: assignee
                  ColumnType: STRING
                  ColumnLength: 255
                  ColumnNullable: true
                - ColumnName: author_login
                  ColumnType: STRING
                  ColumnLength: 255
                  ColumnNullable: true
                - ColumnName: action_plan_key
                  ColumnType: STRING
                  ColumnLength: 50
                  ColumnNullable: true
                - ColumnName: issue_attributes
                  ColumnType: STRING
                  ColumnLength: 4000
                  ColumnNullable: true
                - ColumnName: effort
                  ColumnType: INT8
                  ColumnNullable: true
                - ColumnName: created_at
                  ColumnType: INT8
                  ColumnNullable: true
                - ColumnName: updated_at
                  ColumnType: INT8
                  ColumnNullable: true
                - ColumnName: issue_creation_date
                  ColumnType: INT8
                  ColumnNullable: true
                - ColumnName: issue_update_date
                  ColumnType: INT8
                  ColumnNullable: true
                - ColumnName: issue_close_date
                  ColumnType: INT8
                  ColumnNullable: true
                - ColumnName: tags
                  ColumnType: STRING
                  ColumnLength: 4000
                  ColumnNullable: true
                - ColumnName: component_uuid
                  ColumnType: STRING
                  ColumnLength: 50
                  ColumnNullable: true
                - ColumnName: project_uuid
                  ColumnType: STRING
                  ColumnLength: 50
                  ColumnNullable: true
                - ColumnName: issue_type
                  ColumnType: INT8
                  ColumnNullable: true
                TableColumnsTotal: 26
        ServiceAccessRoleArn: 
          Fn::GetAtt: BucketRole.Arn
      Tags: 
        - Key: PLATFORM
          Value: SAPC01

  TargetTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: 
        Ref: TableName

  TargetEndpoint:
    Type: AWS::DMS::Endpoint
    Properties: 
      DynamoDbSettings:
        ServiceAccessRoleArn: 
          Fn::GetAtt: TargetTableAccessRole.Arn
      EndpointType: target
      EngineName: dynamodb
      Tags: 
        - Key: PLATFORM
          Value: SAPC01

  TargetTableAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TargetTableAccessRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - dms.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Path: "/"

  ReplicationInstance: 
    Type: AWS::DMS::ReplicationInstance
    Properties: 
      ReplicationInstanceClass: dms.t3.medium
      PubliclyAccessible: false
      Tags: 
        - Key: PLATFORM
          Value: SAPC01

  ReplicationTask: 
    Type: AWS::DMS::ReplicationTask
    Properties: 
      MigrationType: full-load
      ReplicationInstanceArn: 
        Ref: ReplicationInstance
      SourceEndpointArn: 
        Ref: S3Endpoint
      ReplicationTaskSettings:
        # In order to enable logs. As per https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Tasks.CustomizingTasks.TaskSettings.html
        Fn::Yaml2Json:
          TargetMetadata:
            TargetSchema: ''
            SupportLobs: true
            FullLobMode: false
            LobChunkSize: 64
            LimitedSizeLobMode: true
            LobMaxSize: 32
            InlineLobMaxSize: 0
            LoadMaxFileSize: 0
            ParallelLoadThreads: 0
            ParallelLoadBufferSize: 0
            BatchApplyEnabled: false
            TaskRecoveryTableEnabled: false
            ParallelLoadQueuesPerThread: 0
            ParallelApplyThreads: 0
            ParallelApplyBufferSize: 0
            ParallelApplyQueuesPerThread: 0
          FullLoadSettings:
            TargetTablePrepMode: DROP_AND_CREATE
            CreatePkAfterFullLoad: false
            StopTaskCachedChangesApplied: false
            StopTaskCachedChangesNotApplied: false
            MaxFullLoadSubTasks: 8
            TransactionConsistencyTimeout: 600
            CommitRate: 10000
          Logging:
            EnableLogging: true
            LogComponents:
            - Id: DATA_STRUCTURE
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: COMMUNICATION
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: IO
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: COMMON
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: FILE_FACTORY
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: FILE_TRANSFER
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: REST_SERVER
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: ADDONS
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: TARGET_LOAD
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: TARGET_APPLY
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: SOURCE_UNLOAD
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: SOURCE_CAPTURE
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: TRANSFORMATION
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: SORTER
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: TASK_MANAGER
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: TABLES_MANAGER
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: METADATA_MANAGER
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: PERFORMANCE
              Severity: LOGGER_SEVERITY_DEFAULT
            - Id: VALIDATOR_EXT
              Severity: LOGGER_SEVERITY_DEFAULT
          ControlTablesSettings:
            historyTimeslotInMinutes: 5
            ControlSchema: ''
            HistoryTimeslotInMinutes: 5
            HistoryTableEnabled: false
            SuspendedTablesTableEnabled: false
            StatusTableEnabled: false
          StreamBufferSettings:
            StreamBufferCount: 3
            StreamBufferSizeInMB: 8
            CtrlStreamBufferSizeInMB: 5
          ChangeProcessingDdlHandlingPolicy:
            HandleSourceTableDropped: true
            HandleSourceTableTruncated: true
            HandleSourceTableAltered: true
          ErrorBehavior:
            DataErrorPolicy: LOG_ERROR
            DataTruncationErrorPolicy: LOG_ERROR
            DataErrorEscalationPolicy: SUSPEND_TABLE
            DataErrorEscalationCount: 0
            TableErrorPolicy: SUSPEND_TABLE
            TableErrorEscalationPolicy: STOP_TASK
            TableErrorEscalationCount: 0
            RecoverableErrorCount: -1
            RecoverableErrorInterval: 5
            RecoverableErrorThrottling: true
            RecoverableErrorThrottlingMax: 1800
            RecoverableErrorStopRetryAfterThrottlingMax: false
            ApplyErrorDeletePolicy: IGNORE_RECORD
            ApplyErrorInsertPolicy: LOG_ERROR
            ApplyErrorUpdatePolicy: LOG_ERROR
            ApplyErrorEscalationPolicy: LOG_ERROR
            ApplyErrorEscalationCount: 0
            ApplyErrorFailOnTruncationDdl: false
            FullLoadIgnoreConflicts: true
            FailOnTransactionConsistencyBreached: false
            FailOnNoTablesCaptured: true
          ChangeProcessingTuning:
            BatchApplyPreserveTransaction: true
            BatchApplyTimeoutMin: 1
            BatchApplyTimeoutMax: 30
            BatchApplyMemoryLimit: 500
            BatchSplitSize: 0
            MinTransactionSize: 1000
            CommitTimeout: 1
            MemoryLimitTotal: 1024
            MemoryKeepTime: 60
            StatementCacheSize: 50
  # PostProcessingRules: {}
  # CharacterSetSettings: {}
  # LoopbackPreventionSettings: {}
  # BeforeImageSettings: {}

      TableMappings: 
        # Can use Fn::Sub as the 'attribute-mappings' already uses the ${} syntax :(
        Fn::Yaml2Json:
          rules:
          - rule-type: selection
            rule-id: 1
            rule-name: "SelectAllTables"
            object-locator:
              schema-name: sonarqube
              table-name: "issues"
            rule-action: include
            filters: []
          - rule-type: object-mapping
            rule-id: 2
            rule-name: "TransformToDDB"
            rule-action: map-record-to-record
            object-locator:
              schema-name: sonarqube
              table-name: issues
            target-table-name: issues
            mapping-parameters:
              partition-key-name: id
              exclude-columns:
                - id
                - kee
              attribute-mappings:
                - target-attribute-name: id
                  attribute-type: scalar
                  attribute-sub-type: string
                  value: "${id}"
      TargetEndpointArn: 
        Ref: TargetEndpoint

Outputs:
  S3Url:
    Description: The Bucket
    Value:
      Fn::Sub: "s3://${Bucket}/${SchemaName}/${TableName}/LOAD00000001.csv"

  ReplicationTaskArn:
    Description: The ReplicationTask Arn
    Value:
      Ref: ReplicationTask

  ServiceAccessRoleArn:
    Description: The AssessmentRole
    Value:
      Fn::GetAtt: DmsCloudwatchLogsRole.Arn

  ResultLocationBucket:
    Description: The ResultLocationBucket
    Value:
      Ref: LogBucket

  ResultLocationFolder:
    Description: The ResultLocationFolder
    Value: "dms"
