version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ResourcePolicyVsRolePolicy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zxwujopwdmuhc"
s3_prefix = "ResourcePolicyVsRolePolicy"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"

tags = "PROJECT=\"SAPC01\" APPLICATION=\"SAPC01\" ENVIRONMENT=\"POC\""
